force-app/main/default/objects/Media_Files_Object_Setting__c/Media_Files_Object_Setting__c.object-meta.xml
<CustomObject>
    <label>Media Files Object Setting</label>
    <nameField>
        <displayFormat>MF-{00000}</displayFormat>
        <label>Media Files Object Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Files Object Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Media_Files_Object_Setting__c/fields/File_Size_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Size_Field_API_Name__c</fullName>
    <label>File Size Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Media_Files_Object_Setting__c/fields/File_Type_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Type_Field_API_Name__c</fullName>
    <label>File Type Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Media_Files_Object_Setting__c/fields/Name_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Name_Field_API_Name__c</fullName>
    <label>Name Field API Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Media_Files_Object_Setting__c/fields/Parent_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Field_API_Name__c</fullName>
    <label>Parent Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Media_Files_Object_Setting__c/fields/Source_URL_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_URL_Field_API_Name__c</fullName>
    <label>Source URL Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SOQLQueryBuilder.cls
/**
* Description	: 	This controller created to make soql queries.
* 
* Created Date  : 	06/10/2020
* 
* Created By	: 	Nikita Kumari
* 
* Revision Logs :   v_1.0 Created
**/
public class SOQLQueryBuilder {

    /**
    * Description	: 	This method create query string for selected sObject.
    * 
    * Params		: 	List, Id, String, Map
    * 
    * Return		:   ResponseUtility
    **/
    public static String createSobjectQueryString( List<Media_Files_Object_Setting__c> fileObjSettings, Id recordId, String mediaFileFilter ) {
     
        //intialize variable
        String queryString = '';
        
        if(  fileObjSettings.size() > 0 && recordId != null && String.isNotBlank( mediaFileFilter )) {
            
            queryString = 'SELECT ' + checkStringIsBlank( fileObjSettings[0].Name_Field_API_Name__c ) 
                					+ checkStringIsBlank( fileObjSettings[0].Source_URL_Field_API_Name__c ) 
                					+ checkStringIsBlank( fileObjSettings[0].File_Type_Field_API_Name__c ) 
                					+ checkStringIsBlank( fileObjSettings[0].File_Size_Field_API_Name__c ) 
                					+ ' CreatedDate FROM ' + fileObjSettings[0].Object_API_Name__c
                					+ ' WHERE ' + fileObjSettings[0].Parent_Field_API_Name__c
                					+ ' = \'' + String.escapeSingleQuotes(recordId) + '\' AND ' + fileObjSettings[0].File_Type_Field_API_Name__c 
                					+ ' IN :mediaTypeValues ORDER BY LastModifiedDate Desc';
             
        }
        
        return queryString;
    }
      
    /**
    * Description	: 	This method check text field value is blank or not.
    * 
    * Params		: 	String
    * 
    * Return		:   String
    **/
    public static String checkStringIsBlank( String fileObjSettingField ) {
     
        return String.isNotBlank( fileObjSettingField ) ? fileObjSettingField + ', ' : '';	
    }
}